### ISSUE TITLE
Praskají bublinky? Vrzají esíčka?

### ISSUE THREAD

**Issue by vaclavstepan** [ODZ-UJF-AV-CR/balon#13]
Máří včera nadnesla, že bublinky fakt popraskaj. Jestli jo, budem mít problém s tepelnou izolací a dopadem do tvrdého.

Koupil jsem preventivně na poště dva balíky esíček (je to něco jako lehký polystyren s uzavřenými póry). Možná to bude vrzat a rušit (zkusím testnout).

Bylo by fajn zkusit, jestli bublinky fakt praskaj nebo nepraskaj (v 30 km ekvivalentním tlaku).

**Comment by vaclavstepan** [comment]
Dáša říká, že tlak v 30 km je cca 11 hPa.

**Comment by kaklik** [comment]
Nevim jak takový tlak teď vyrobit. To už chce olejovou vývěvu..  Na FEL je na to sice simulátor, ale ten je nepoužitelnej.. Dostat se k němu je birokracie na dva dny. A tolik času nemáme.

**Comment by kakl** [comment]
Svetlik ma vyvevu, ale sklenena nadoba neni moc velka. Bublinky by 
vyzkouset sly.

**Comment by vaclavstepan** [comment]
Jo, stačí pár bublinek a nebo ověřit, že esíčka nedělaj rušení.

On Wednesday, 16 December 2015, KAKL notifications@github.com wrote:

> Svetlik ma vyvevu, ale sklenena nadoba neni moc velka. Bublinky by
> vyzkouset sly.
> 
> On 16.12.2015 22:37, Jakub Kákona wrote:
> 
> > Nevim jak takový tlak teď vyrobit. To už chce olejovou vývěvu.. Na FEL
> > je na to sice simulátor, ale ten je nepoužitelnej.. Dostat se k němu
> > je birokracie na dva dny. A tolik času nemáme.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ODZ-UJF-AV-CR/balon/issues/13#issuecomment-165248007
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ODZ-UJF-AV-CR/balon/issues/13#issuecomment-165263473.

## 

Department of Radiation Dosimetry, Nuclear Physics Institute ASCR, Prague,
Czech Republic

**Comment by vaclavstepan** [comment]
Esíčka byly shledány použitelnými. Bublinky byly shledány nepoužitelnými.
