### ISSUE TITLE
Altimet failure

### ISSUE THREAD

**Issue by vaclavstepan** [ODZ-UJF-AV-CR/balon#23]
Občas z neznámých důvodů přestane fungovat vyčítání Altimetu. Přitom ostatní věci na i2c běží.

**Comment by kakl** [comment]
Zkusime ho  vymenit.
Dne 17.12.2015 13:31 napsal uživatel "vaclavstepan" <
notifications@github.com>:

**Comment by vaclavstepan** [comment]
Martin vyměnil, zatím to běží.
