### ISSUE TITLE
Battery monitor

### ISSUE THREAD

**Issue by vaclavstepan** [ODZ-UJF-AV-CR/balon#25]
Battery monitor reports nonsenses:

`BatTemp: -427.35 C RemCap: -1542 mAh FullCap: -1542 mAh U: -1542 mV I: -67078 mA Charge: -1542.00 %`

**Comment by kaklik** [comment]
Za jakých podmínek se to stane?

**Comment by vaclavstepan** [comment]
Pokud je SDA z baterky připojený na VCC na I2C hubu. Tak solved.

**Comment by vaclavstepan** [comment]
Martin Kákona vyřešil konektorem na I2C hubu, který zmenšuje možnost zapojit to blbě.
