### ISSUE TITLE
Anténa pro LoRa

### ISSUE THREAD

**Issue by kaklik** [ODZ-UJF-AV-CR/balon#30]
Již [navrženou QFH anténu](https://github.com/ODZ-UJF-AV-CR/balon/blob/master/CAD/STL/Telemetry_helix_868.stl) pro vysílač balonu je potřeba integrovat do konstrukce gondoly, nebo přídavné gondoly s telemetrickým vysílačem. 

Předpokládám, že anténa bude připevněna na spodní stranu polystyrénové gondoly. Smyslem antény je vyzařovat do spodní hemisféry. Anténa má být právě v této charakteristice lepší, než obyčejná GP anténa, která vyzařuje do torusu, který ale ve výšce letu balonu nebude pokryt přijímacími stanicemi. Neboť nejbližší, přijímací stanice budou pod balonem.

**Comment by cernohorsky** [comment]
Povedlo se mi postavit a změřit tuhle QFH anténu pro 868 MHz, ale první výsledky byli neuspokojivé. Ukázalo se, že samotný model přidává anténě parazitní kapacitu a výrazně ji rozladí. Pomocí [kalkulátoru](http://jcoppens.com/ant/qfh/calc.en.php) jsem ji přepočítal na vyšší frekvenci a upravil 3D model. Po několika iteracích jsem se dostal na požadovanou frekvenci.

https://github.com/cernohorsky/QFH-Antenna-868MHz

Zbýva dořešit 2 věci:
1. Myslím, že by bylo potřebné změnit "Width/height ratio" aby jsme dosáhli větší směrovosti. http://jcoppens.com/ant/qfh/sim.en.php
2. Vyřešit symetrizaci antény. Teď je anténa přizpůsobená na 50 ohmů (VSWR 1.32), ale přívodní koax může ovlivňovat vyzařovací charakteristiku. Myslím, že by chtělo přidat na feed point balun, nebo aspoň ferrit.

**Comment by kaklik** [comment]
Nejsem si jistý, jestli větší směrovost je zrovna to, co je potřeba. Neboť když balon bude už nízko, tak je stále potřeba, aby byl přijímatelný stanicemi. Takže bych navrhoval směrovost antény naopak snížit,

Symetrizace antény - zde očekávám, že by měl stačit ferit a ověřit směrovou charakteristiku třeba nějakou mustikoptérou.  Kdybys chtěl používat balun, tak jaký typ bys navrhoval zvolit?

**Comment by cernohorsky** [comment]
S tou smerovosti uprimne nevim, rikal jsem si, ze primat telemetrii na 30 km vzdalenost chce co nejvetsi zisk. Ale je pravda ze pri nizkych vyskach se situace obraci. Predpokladam ze dohledavani te sondy je priorita.
Jinak mne osobne se libi [tenhle balun](https://www.mouser.de/ProductDetail/TDK/HHM1776B2?qs=sGAEpiMZZMtMMXztyU6kdOdUWOFyD2Vg34FvfaQeCSr2%252BHAZXJE1HA%3D%3D)

Ale skutecne je potreba tu antenu nejdriv zkusit, pokud bude fungovat uz bych do ni nerejpal...

**Comment by kaklik** [comment]
Ano konečné dohledání je priorita. Ze zkušeností z předchozích letů vyplývá, že zisk přenosu v maximální výšce není třeba řešit, neboť v případě sigfoxu balon viděly stovky stanic po celé Evropě (byla použita 1/2 GP anténa ). To že balon vidělo tolik stanic byl problém, neboť síť ta takovou situaci není stavěná a o některé zprávy se díky tomu přišlo, navíc zpracování zpráv trvalo hodiny.  Proto je výhodné směrovou charakteristiku omezit na vyzařování dolu, ale ne moc, aby ve svazku vždy nějaká gateway byla. 

Ten balun je zajímavý ale má Insertion Loss: 1.2 dB. Předpokládám, že je to tím že je velmi malý. Neexistuje nějaká jeho varianta, která by byla větší a tím pádem měla i menší ztráty?  
Použití takového balonu bych asi viděl jako optimální, pokud by LoRa modem byl přímo součástí antény. Což by bylo dobré v případě, že by od antény mohly vést přímo SPI vodiče do autopilota viz issue #26

**Comment by cernohorsky** [comment]
Bohuzel zadny lepsi jsem nenasel. Jinak optimalni by podle mne bylo kdyby ten balun byl primo ve feed point. Nejlepsi by byla mala DPS kde by se knemu pripojili jednotlive segmenty anteny. Ale jelikoz je ten Insertion Loss tak velky uvazoval bych o tom jen kdyz to bude potreba.
A nemyslim si ze je dobre integrovat LoRa modem s antenou. RFM95 dokaze pracovat max. do -20 °C.

**Comment by kaklik** [comment]
To je docela škoda, ten modem neintegrovat s anténou, protože by to vyřešilo napájení antény a stejně pro LoRa modem bude zřejmě potřeba udělat PCB.  
Modem by ale mohl být připojený k anténě dvojlinkou (podobně jako navrhuji v issue #33 ), což by umožnilo ho dát do gondoly, kde nezmrzne. 

Ten PCB pro nějaký LoRa modul ale bude potřeba tak jako tak, neboť LoRa modem je potřeba připojit na [SPI port](https://pixhawk.org/pixhawk-connector-standard/) autopilota, který má [JST-GH konektory](http://www.jst-mfg.com/product/detail_e.php?series=105) předpokládám že autopilot se pak s modemem propojí 7pinovým kablíkem 1:1 s těmito konektory.

**Comment by cernohorsky** [comment]
Puvodne jsem myslel ze pouzijeme tohle:
https://github.com/hallard/Mini-LoRa
Je totiz pripravena na SMA (nebo UFL) konektor. Mam osazene 2 DPS a dalsich 8 neosazenych. Btw. tato DPS musi byt napajena z 3,3V a doufam ze i ten autopilot komunikuje na 3,3V...
Ale muzeme pouzit i moji DPS:
https://github.com/cernohorsky/LoRa-Node
ISP konektor je vlastne SPI rozhrani. Antenu bych odrezal a dobastlil tam nejak SMA konektor. Bude to sice trochu bastl, ale slo by to pouzit hned a tahle varianta by byla urcite ta nejmensi a nejlehci.

**Comment by kaklik** [comment]
Ano, podle odkazu, který jsem poslal autopilot komunikuje na 3V3 a poskytuje 5V napájení. 

Když se dívám do schéma těch desek, tak ani jedna není uzpůsobena na 5V napájení od autopilota navíc ten CPU je tam zřejmě nadbytečný.  Viděl bych to tak spíš na nakreslení nové desky, speciálně pro připojení k autopilotovi.  Nezdá se mi moc nápad tam SMA konektor "nějak dobastlit", když na tom závisí, jestli ten balon najdeme. 
Úprava firmware ale na těchto deskách zřejmě otestovat jde.

**Comment by cernohorsky** [comment]
Klidne tu DPS navrhnu. Ale ten mikrokontroler tam je dulezity. RFM95 je "hloupy" modul a knihovna LMIC musi udalat cely "LoRa stack". Tohle je dan za tu nizkou cenu...

**Comment by kaklik** [comment]
Mě to právě přijde bezpečnější mít v tom driveru v autopilotovi, než tam mít další Arduino.  Co si o tom myslíš @povik ?

**Comment by kaklik** [comment]
Ještě je pak možnost použít [modul od microchipu](https://www.microchip.com/wwwproducts/en/RN2483), ale tam je ten procesor akorát schovaný uvnitř toho modulu. Což sice chápu, že pravděpodobně zjednodušuje vývoj software, ale zároveň je to další vrstva, kterou se vzdalujeme od kontroly nad tím hardware. Takže můžou vznikat různé potíže při inicializaci a nebo při resetu.

**Comment by povik** [comment]
@kaklik Podívám se, co obnáší posílání zpráv přes RFM95, a dám vědět.

**Comment by kaklik** [comment]
@povik Možná ti ušetřím trochu času informací že [RFM95](https://cdn.sparkfun.com/assets/learn_tutorials/8/0/4/RFM95_96_97_98W.pdf) a třeba [tenhle modul](http://www.dorji.com/docs/data/DRF1276G.pdf) ve skutečnosti používají ten [stejný čip SX1276](https://www.semtech.com/products/wireless-rf/lora-transceivers/sx1276#download-resources)
A liší se především tím, že já mám DRF1276G se stíněnou krabičkou a @cernohorsky  má RFM95 na svém modulu. Možná by bylo nejlepší se na tyhle mezimoduly vykašlat a prostě použít přímo třeba čip [SX1262](https://www.semtech.com/products/wireless-rf/lora-transceivers/sx1262) a postavit na něm plnohodnotný MLAB modul. Výhodou takového řešení by byly známé a pravděpodobně lepší parametry použitých komponent a použití novějšího transceiveru s větším výstupním výkonem (+22 dBm)

**Comment by cernohorsky** [comment]
Ten SX1262 vypada moc pekne a rad takovy modul udelam, ale SW je uz nad me sily. Tuhle knihovnu ted pouzivam: https://github.com/matthijskooijman/arduino-lmic
Myslite ze by sla ohnout na ten SX1262?

**Comment by kaklik** [comment]
@cernohorsky  Netuším, jak ta knihovna funguje, takže nevím. Přijde mi podivný, že potřebuje to připojení na IO piny, každopádně jestli to jde, tak si myslim, že to pro Arduino dřív nebo pozdějc někdo udělá. 

Teď ale momentálně řešíme, jak to nejlépe připojit do [PX4](https://github.com/PX4/Firmware/tree/master/src/drivers/telemetry).

**Comment by cernohorsky** [comment]
Tohle jsem nasel v dokumentaci LMIC (README.md na github strance):
"The LMIC library was intended to connect the DIO pins to interrupt lines and run code inside the interrupt handler. However, doing this opens up an entire can of worms with regard to doing SPI transfers inside interrupt routines (some of which is solved by the Arduino beginTransaction() API, but possibly not everything). One simpler alternative could be to use an interrupt handler to just store a timestamp, and then do the actual handling in the main loop (this requires modifications of the library to pass a timestamp to the LMIC radio_irq_handler() function)."

Celkove je cela ta sekce "Timing" hodne zajimava...

**Comment by povik** [comment]
Tak závěr je takový, že vzhledem k dostupným knihovnám můžeme ovládat SX1262 nebo SX1276 přímo z autopilota.

**Comment by kaklik** [comment]
Dobře, v tom případě jsem přímo pro použití SX1262 kvůli většímu výkonu. Dále to navrhuji řešit v tomto issue: https://github.com/ODZ-UJF-AV-CR/balon/issues/26
A tohle nechat pro záležitosti související s anténou. 

@ChroustJan zřejmě je tak jasná konstrukce modulu.  Potíž s připojením na SPI budeme řešit na straně autopilota, nikoliv na straně modemu.

**Comment by cernohorsky** [comment]
Ty knihovny resi skutecne LoRa-WAN komunikaci? SX1276 totiz umi i point to point LoRa a obycejnou FSK komunikaci a ty se nam vubec nehodi...

**Comment by povik** [comment]
@cernohorsky Je to tak, řeší i LoRaWAN. Třeba tady jsem našel implementaci uvolněnou Semtechem.

https://github.com/Lora-net/LoRaMac-node

**Comment by cernohorsky** [comment]
OK potom je vse v poradku. Klidne tu DPS pro SX1262 navrhnu, ale rikam si jestli to stoji za namahu. Chvili potrva nez to udelam a pak se bude dlouho cekat na tistaky. A beztak budu muset jen zkopirovat referencni design. Nebylo by lepsi koupit evaluation module primo od semtechu?
https://www.mouser.de/ProductDetail/Semtech/SX1262MB2CAS?qs=sGAEpiMZZMve4%2FbfQkoj%252BAzdA%252BRQ3Wp6c6o1n8LL7p0%3D
Takhle bude mozne postavit funkcni protoyp do par dni...

**Comment by kaklik** [comment]
Dohodl jsem se s @povik  že zatím sestavím testovací desku s RFM95. Neboť pokud bude aplikovatelná knihovna od Semtechu, tak by pro software neměl být rozdíl čipů překážkou. 
Ty tak máš více času na návrh té správné DPS s SX1262 můžete na tom klidně pracovat i nějak společně s @ChroustJan

**Comment by ChroustJan** [comment]
Ahoj, modul mám rozpracovaný. Určitě půjde spolupracovat.

**Comment by kaklik** [comment]
U antény je potřeba ještě doplnit mřížku na uchycení ze spodu gondoly. V [mém kódu](https://github.com/kaklik/QFH-Antenna-433MHz/blob/master/QFH-Antenna-433MHz.scad#L76) jsem mřížku poupravil pro lepší tiskutelnost. 

Také by asi nebylo špatné do modelu antény implementovat stejné odlehčení stěn.

**Comment by kaklik** [comment]
Model od @cernohorsky  Jsem postupně upravil tak že jsem L/D ratio změnil až na 0.85 a přidal odlehčení a spodní mřížku sloužící k uchycení. 

![obrazek](https://user-images.githubusercontent.com/1194177/69811904-681fec80-11ef-11ea-950a-9fa934d5d085.png)

Výsledkem je anténa s ostrým minimem na rezonanční frekvenci. 

![antenna868](https://user-images.githubusercontent.com/1194177/69812315-2ba0c080-11f0-11ea-8e5f-e354e7a5c4bc.png)
