### ISSUE TITLE
Zlepšit způsob připojení antén k balonu

### ISSUE THREAD

**Issue by kaklik** [ODZ-UJF-AV-CR/balon#40]
Aktuální konstrukce antén pod gondolou funguje dobře, jako absorber nárazu při dopadu. 
Antény je však potřeba po nárazu do země vyměnit za nové, neboť typicky dojde k prasknutí plastových dílů. 
Překážkou k této operaci je nutnost odletování a zpětného zaletování smyček antény na přívodní koax, což je časově náročná operace, která trvá přes hodinu. 
Podstatně by to však mohly změnit dvě konstrukční úpravy.

- [x] Antény přichytit na suchý zip zespodu gondoly
- [x] Vyřešit [potíž s připojením koaxiálního kabelu](https://github.com/cernohorsky/QFH-Antenna-868MHz/issues/1).

**Comment by kaklik** [comment]
Výrazně by tomuto mohla pomoci úprava balunu od @cernohorsky  
Viz: https://github.com/cernohorsky/AntennaBalun/issues/1

**Comment by kaklik** [comment]
### Připojení antény ke koaxiálnímu kabelu 

@cernohorsky  Navrhl úpravu svého balunu k dipolové anténě, která řeší problém s připojením kabelu k anténě. 
Je zde: https://github.com/ODZ-UJF-AV-CR/QFHBAL01

@ChroustJan Ten plošný spoj jde rozměrově trochu upravit. Myslíš že pak bude možné jej přidat k nějaké aktuální výrobě PCB? 

### Uchycení antény na gondolu 

Anténa momentálně má na spodní straně vytištěnou mřížku, která sloužila k připevnení ke gondole lepící páskou. Tento způsob připojení se celkem osvědčil, ale není moc flexibilní.

![image](https://user-images.githubusercontent.com/1194177/97325970-ccba5000-1873-11eb-9ee4-a78a29b565cc.png)

Navrhoval bych mřížku upravit tak, aby v rozích byly plné čtverečky na které se přilepí [samolepící suchý zip](https://www.azktrade.cz/3m-sj3550-dual-lock-samolepici-suchy-zip-cerny-4/).  Stejný suchý zip by pak byl nalepen ze spodní strany na gondole. 
Anténu by mohl upravit někdo, kdo dovede pracovat s OpenSCADem. Třeba @Alsa-Tucnak  ?

**Comment by Alsa-Tucnak** [comment]
Anténu upravit můžu. Jen je potřeba zajistit opravdu dobře její uchycení. U té mřížky mi přijde, že je dost velká p-st, že se od spirály odlomí. 4 suché zipy v rozích by mohly držet dobře snad. Zkusím tedy sehnat suchý zip a upravit anténu.

**Comment by kaklik** [comment]
> Anténu upravit můžu. Jen je potřeba zajistit opravdu dobře její uchycení. U té mřížky mi přijde, že je dost velká p-st, že se od spirály odlomí. 4 suché zipy v rozích by mohly držet dobře snad. Zkusím tedy sehnat suchý zip a upravit anténu.

Super! :)  Nevím jak to myslíš s tím odlomením mřížky od spirály.  Přijde mi, že by došlo k úplně destrukci antény, kdyby se tohle mělo ulomit. 

Jinak do toho komentáře výše jsem dal odkaz na konkrétní typ suchého zipu (dual-lock), který by se tam myslím měl použít.

**Comment by kaklik** [comment]
Jinak prostřední část té 3D mřížky ve spodní části antény bude potřeba upravit tak, aby na ní bylo možné připevnit [tento plošný spoj](https://github.com/ODZ-UJF-AV-CR/QFHBAL01).

Dovedu si představit, že by to bylo realizované tak, že na mřížce budou vytištěny 3 trny, které zapadnou do třech montážních děr tohoto plošného spoje.  Tím by byla i definována jeho orientace, neboť tam musí být upevněn ve správné rotaci. 

Potom ty tři vytištěné trny půjdou rozmáčknout něčím horkým, aby z nich plošný spoj nespadl. 

Anténa by se tak sundavala jako celek, kdy se připojí kabel do konektoru plošného spoje a celá anténa se přilepí na suché zipy.

**Comment by kaklik** [comment]
Zde jsem [exportoval rozměrový výkres QFHBAL01](https://github.com/ODZ-UJF-AV-CR/QFHBAL01#mechanical-drawing)

![QFHBAL dimensions](https://raw.githubusercontent.com/ODZ-UJF-AV-CR/QFHBAL01/QFHBAL01A/doc/src/img/dimensions.png)

**Comment by kaklik** [comment]
Nový kód jsem sloučil s původnim kódem, aby nevznikalo  příliš mnoho variant (původní anténa už nemá žádné využití). 

Řešení kdy plošný spoj bude nasazen na kuželové trny, je docela revoluční, ale asi dobré. Neboť takhle není nutné řešit přesné tolerance otvorů :)

![image](https://user-images.githubusercontent.com/1194177/100108656-4e999b00-2e6b-11eb-92c7-afb7145cc4fb.png)

Průměr otvoru v PCB je 3.2mm. To jsem na obrázku výše zapomněl. Pro aktuální trn to znamená, že zřejmě plošný spoj bude někde lehce pod polovinou výšky trnu. Což je zřejmě správně. :)

Potíž nastává s umístěním trnů a s otvorem pro koaxiální konektor, který musí být vyveden zřejmě ze spodní strany. 

Plošný spoj myslím si, bude umístěn osově přesně na druhou stranu. Tj. takhle. (Tohle pak musím ještě znovu zkontrolovat - v kódu by na to bylo dobré udělat přepínátko.)


![image](https://user-images.githubusercontent.com/1194177/100113529-b4d4ec80-2e70-11eb-8aab-df0e7cd81436.png)

Zatím jsem do antény doplnil pouze vrstvu "QFHBAL01-User_Comments.dxf" na které jsou vidět kóty a obrysy. 

Další potíš je domnívám se ta, že aktuálně pozice RF konektoru vychází přesně do křížení mřížky. 
Tady jsem vytvořil nový obrázek, který má doplněny kóty ke konetoru. 

![dimensions](https://user-images.githubusercontent.com/1194177/100114897-32e5c300-2e72-11eb-9274-d7e74c20b68e.png)

Konektor potřebuje ze spodní strany kruh volného prostoru o průměru minimálně 8mm, aby do něj bylo možné připojit nebo odpojit koaxiální kabel.

**Comment by kaklik** [comment]
Tak správná orientace QFHBAL na spodní straně antény je tahle: 

![image](https://user-images.githubusercontent.com/1194177/100285395-1ed4bb00-2f71-11eb-9555-198494f02f90.png)

Čevené značky SCAD souboru jsou sesouhlaseny s orintací PCB na levém obrázku.

Parametry rozměrů, které jsou nyní [přímo v kódu antény](https://github.com/ODZ-UJF-AV-CR/QFH-Antenna/blob/e0976c53d5830cff4555565b1e6811471ef7c436/QFH-Antenna.scad#L47-L57) by měly být přesunuty do [souboru s parametry](https://github.com/ODZ-UJF-AV-CR/QFH-Antenna/blob/master/parameters.scad).

**Comment by kaklik** [comment]
Antény byly přilepeny 3M dual-lock suchým zipem na víko gondoly.
