### ISSUE TITLE
Correct time initialization via GPS

### ISSUE THREAD

**Issue by vaclavstepan** [ODZ-UJF-AV-CR/balon#9]

**Comment by kaklik** [comment]
We have the same problem at Bolidozor's network stations. I have tried to resolve this trouble by using ntp-wait: http://linux.die.net/man/8/ntp-wait and gpsd configured as NTP server. But I am not able to get it working. 
http://www.rjsystems.nl/en/2100-ntpd-garmin-gps-18-lvc-gpsd.php

**Comment by vaclavstepan** [comment]
gpsd provides the date once it is connected to the GPS, but time is set to 00:00:00. After it gets fix, the time is available. So at this moment I query the GPS fix mode at startup and if GPS has fix, it is used to set the time.
